  version: 2.1
  orbs:
    #ncsorb2: neocortix/ncsorb2@dev:alpha
    ncsorb2: neocortix/ncsorb2@volatile
  
  jobs:
    build:
      docker: 
        - image: circleci/node:4.8.2
      steps:
        - checkout # check out the code in the project directory
        - run: echo would BUILD code here
    testXXXX:
      docker:
        - image: circleci/python:3.6 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory

        - ncsorb2/loadtest:
            targetHostUrl: "https://codero2.neocortix.com"
            nWorkers: 3
            susTime: 30
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - ncsorb2/loadtest:
            requires:
              - build
            branch: Alpha
            targetHostUrl: "https://codero2.neocortix.com"
            nWorkers: 30
            rampUpRate: "1"
            usersPerWorker: 7
            susTime: 240

