  version: 2.1
  orbs:
    #myOrb: neocortix/loadtest@dev:alpha
    myOrb: neocortix/loadtest@volatile
  
  jobs:
    build:
      docker: 
        - image: circleci/node:4.8.2
      steps:
        - checkout # check out the code in the project directory
        - run: echo would BUILD code here

    badCmdJob:
      docker:
        - image: circleci/node:8
      steps:
        - myOrb/loadtest:
            targetHostUrl: "https://codero2.neocortix.com"
            nWorkers: 3
            susTime: 30
    goodCmdJob:
      docker:
        - image: circleci/python:3.6
      steps:
        - myOrb/loadtest:
            targetHostUrl: "https://codero2.neocortix.com"
            nWorkers: 3
            susTime: 30
  workflows:
    version: 2
    build_and_test:
      jobs:
        #- build
        #- goodCmdJob
        #- badCmdJob
        - myOrb/loadtest:
            requires:
              #- build
              #- goodCmdJob
              #- badCmdJob
            #branch: Alpha
            targetHostUrl: "https://codero2.neocortix.com"
            nWorkers: 3
            rampUpRate: "2"
            regions: >-
              north-america russia-ukraine-belarus
            usersPerWorker: 7
            susTime: 30
            targetUris: >-
              /index.html
              /favicon.ico
