  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/python:3.6.8 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: python3 --version
        - run: pip3 --version
        #- run: echo "hello world" # run the `echo` command
