  version: 2.1
  orbs:
    ncsorb2: neocortix/ncsorb2@0.0.1
  
  jobs:
    build:
      docker: 
        - image: circleci/python:3.6 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory

        - ncsorb2/loadtest:
            targetHostUrl: "https://codero2.neocortix.com"
            nWorkers: 3
            susTime: 30
