  version: 2.1
  orbs:
    ncsorb2: neocortix/ncsorb2@dev:alpha
  
  jobs:
    build:
      docker: 
        - image: circleci/python:3.6 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: python3 --version

        - ncsorb2/loadtest:
            nWorkers: 3
        - run: ls -al
