  version: 2.1
  orbs:
    ncsorb2: neocortix/ncsorb2@dev:alpha
  
  commands:
      loadtest:
        description: "run a Neocortix loadtest"
        parameters:
          nWorkers:
            type: integer
            default: 1
        steps:
          #- run: echo loadtesting << parameters.nWorkers >>
          - run: ./runRemoteLoadtest.py https://codero2.neocortix.com --nWorkers << parameters.nWorkers >> --jsonOut loadtest_out.json --masterUrl  https://load-test.cloud.neocortix.com/ --authToken $NCS_AUTH_TOKEN
  jobs:
    build:
      docker: 
        - image: circleci/python:3.6 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: python3 --version
        #- run: ./runRemoteLoadtest.py https://codero2.neocortix.com --nWorkers 3 --jsonOut loadtest_out.json --masterUrl  https://load-test.cloud.neocortix.com/ --authToken "zzz"
        - loadtest:
            nWorkers: 3
        
