  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/python:3.6 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: python3 --version
        - run: ./runRemoteLoadtest.py https://codero2.neocortix.com --nWorkers 3 --jsonOut loadtest_out.json --masterUrl  https://load-test.cloud.neocortix.com/ --authToken "VnvnwNggQz7NDEeMJQQmDfdS85Jjzs4g"
